apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels: 
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hjilakara/webapp
        ports:
        - containerPort: 8080
